import {
  APPOINTMENT_MATRIX_ROLES,
  APPOINTMENT_REQUEST_TRANSITIONS,
  APPOINTMENT_ROUTES,
  APPOINTMENT_STATUSES,
  APPOINTMENT_TRANSITIONS,
  PATIENT_REQUEST_ORIGINS,
  appointmentTransitionMatrix,
  roleHoldsAppointmentPermission,
} from './appointment-lifecycle';

/**
 * Render the appointment lifecycle matrix the release gate publishes.
 *
 * Generating the document from the same table the assertions read is what makes the documentation
 * acceptance criterion enforceable: the file cannot describe a workflow the code does not
 * implement, because a divergence fails the suite rather than sitting unnoticed in a doc nobody
 * re-reads.
 */
export function renderAppointmentLifecycleMatrix(): string {
  const lines: string[] = [];

  lines.push('# Appointment Lifecycle Matrix');
  lines.push('');
  lines.push(
    'Generated by `apps/api/src/patient-portal/appointment-lifecycle-matrix.spec.ts`. Edit the table in',
  );
  lines.push('`apps/api/src/testing/appointment-lifecycle.ts`, not this file.');
  lines.push('');
  lines.push(
    'Every permission below is evaluated against the roles a user holds **at the clinic the',
  );
  lines.push(
    'appointment belongs to**. A role held at another clinic never applies here, and a role held at',
  );
  lines.push('another organization never applies at all.');
  lines.push('');

  lines.push('## Appointment transitions');
  lines.push('');
  lines.push(
    'An appointment row is created already `CONFIRMED` when staff confirm a request, so `CONFIRMED`',
  );
  lines.push('is the only state any action can be applied from. The other three are terminal.');
  lines.push('');
  lines.push('| Action | From | To | Requires | Permission | Audit event |');
  lines.push('| --- | --- | --- | --- | --- | --- |');
  for (const transition of APPOINTMENT_TRANSITIONS) {
    const requires = [
      transition.requiresReason ? 'a reason' : null,
      transition.requiresStarted ? 'the start time to have passed' : null,
    ].filter((entry): entry is string => entry !== null);
    lines.push(
      `| ${transition.label} | ${transition.fromStatuses.join(', ')} | ${transition.toStatus} | ${
        requires.length === 0 ? 'nothing further' : requires.join(' and ')
      } | \`${transition.permission}\` | \`${transition.auditAction}\` |`,
    );
  }
  lines.push('');

  lines.push('### Every state and action pair');
  lines.push('');
  lines.push(
    'A refusal carries `APPOINTMENT_INVALID_TRANSITION` with the current status, the attempted',
  );
  lines.push('action, and the allowed source statuses, and writes nothing.');
  lines.push('');
  lines.push(`| Status | ${APPOINTMENT_TRANSITIONS.map((t) => t.label).join(' | ')} |`);
  lines.push(`| --- | ${APPOINTMENT_TRANSITIONS.map(() => '---').join(' | ')} |`);
  const matrix = appointmentTransitionMatrix();
  for (const status of APPOINTMENT_STATUSES) {
    const cells = APPOINTMENT_TRANSITIONS.map((transition) => {
      const entry = matrix.find((row) => row.status === status && row.action === transition.action);
      return entry?.allowed ? 'allowed' : 'refused';
    });
    lines.push(`| ${status} | ${cells.join(' | ')} |`);
  }
  lines.push('');

  lines.push('## Request transitions');
  lines.push('');
  lines.push('| Action | From | To | Requires | Permission | Audit event |');
  lines.push('| --- | --- | --- | --- | --- | --- |');
  for (const transition of APPOINTMENT_REQUEST_TRANSITIONS) {
    const audit = transition.createsAppointmentAuditAction
      ? `\`${transition.auditAction}\`, \`${transition.createsAppointmentAuditAction}\``
      : `\`${transition.auditAction}\``;
    lines.push(
      `| ${transition.label} | ${transition.fromStatuses.join(', ')} | ${transition.toStatus} | ${
        transition.requiresReason ? 'a reason' : 'nothing further'
      } | \`${transition.permission}\` | ${audit} |`,
    );
  }
  lines.push('');
  lines.push(
    'No route writes `TRIAGED` or a request status of `CANCELLED`. Both are reachable in the schema',
  );
  lines.push('and accepted as a source state, and neither is produced by the system today.');
  lines.push('');

  lines.push('## What a patient can open');
  lines.push('');
  lines.push('| Request | Type | Needs an existing appointment | Requires | Audit event |');
  lines.push('| --- | --- | --- | --- | --- |');
  for (const origin of PATIENT_REQUEST_ORIGINS) {
    lines.push(
      `| ${origin.label} | \`${origin.requestType}\` | ${
        origin.requiresSourceAppointment ? 'yes' : 'no'
      } | ${origin.requiresReason ? 'a reason' : 'nothing further'} | \`${origin.auditAction}\` |`,
    );
  }
  lines.push('');
  lines.push(
    'A change request never mutates the appointment. It records what the patient asked for and',
  );
  lines.push(
    'leaves the decision with staff. The appointment must be `CONFIRMED` and still in the future.',
  );
  lines.push('');

  lines.push('## Reminders');
  lines.push('');
  lines.push('| Action | Queued reminders | Failure reason recorded | New reminder |');
  lines.push('| --- | --- | --- | --- |');
  for (const transition of APPOINTMENT_TRANSITIONS) {
    lines.push(
      `| ${transition.label} | suppressed | \`${transition.reminderSuppressionReason}\` | ${
        transition.schedulesReminder ? 'scheduled' : 'none'
      } |`,
    );
  }
  lines.push('');
  lines.push(
    'Confirming a request schedules the first reminder for 24 hours before the start time, clamped',
  );
  lines.push(
    'to now when that moment has already passed. A suppressed reminder is recorded as `FAILED` and',
  );
  lines.push(
    'stays visible rather than being deleted. A reminder that escapes suppression is checked again',
  );
  lines.push(
    'at send time against the appointment it names, so a stale job still cannot reach a patient.',
  );
  lines.push('');

  lines.push('## Routes');
  lines.push('');
  lines.push('| Route | Clinic from | Permission |');
  lines.push('| --- | --- | --- |');
  for (const route of APPOINTMENT_ROUTES) {
    lines.push(
      `| \`${route.method} ${route.path}\` | ${
        route.clinicScope === 'param' ? 'path parameter' : '`X-Clinic-Id` header'
      } | \`${route.permission}\` |`,
    );
  }
  lines.push('');

  lines.push('## Permissions by role');
  lines.push('');
  lines.push('| Permission | ' + APPOINTMENT_MATRIX_ROLES.join(' | ') + ' |');
  lines.push('| --- | ' + APPOINTMENT_MATRIX_ROLES.map(() => '---').join(' | ') + ' |');
  const permissions = [...new Set(APPOINTMENT_ROUTES.map((route) => route.permission))].sort();
  for (const permission of permissions) {
    const cells = APPOINTMENT_MATRIX_ROLES.map((role) =>
      roleHoldsAppointmentPermission(role, permission) ? 'yes' : 'no',
    );
    lines.push(`| \`${permission}\` | ${cells.join(' | ')} |`);
  }
  lines.push('');
  lines.push(
    'A `SYSTEM_ADMIN` holds every permission through the wildcard grant, and is still admitted to a',
  );
  lines.push(
    'clinic only through `ClinicScopeGuard`. A portal patient reaches no staff route at all.',
  );
  lines.push('');

  return `${lines.join('\n')}\n`;
}
