/**
 * Render the offline and job execution matrix the release checklist publishes.
 *
 * Generated from the same table the drift spec checks, so the document cannot name a test that no
 * longer exists or a manual step the user testing guide does not describe.
 */

import {
  CONDITION_HEADINGS,
  KNOWN_RISKS,
  MATRIX_CONDITIONS,
  OFFLINE_JOB_SCENARIOS,
  OWNER_SURFACES,
  type AutomatedTestRef,
  type KnownRisk,
  type MatrixScenario,
} from './offline-job-matrix';

/** Where a test runs, read from its path: the suites are told apart by name and location. */
export function testKind(file: string): 'Unit' | 'Integration' | 'E2E' {
  if (file.includes('/e2e/')) return 'E2E';
  if (file.includes('.integration.')) return 'Integration';
  return 'Unit';
}

/** Widened so the document still renders once every known risk has been fixed and removed. */
const knownRisks: Readonly<Record<string, KnownRisk>> = KNOWN_RISKS;

const cell = (text: string) => text.replace(/\|/g, '\\|').replace(/\n/g, ' ');

function coverageCell(scenario: MatrixScenario): string {
  const kinds: string[] = [...new Set(scenario.automated.map((test) => testKind(test.file)))];
  if (scenario.manual) kinds.push('Manual');
  return kinds.length > 0 ? kinds.join(', ') : 'None';
}

const testLine = (test: AutomatedTestRef) =>
  `  - ${testKind(test.file)}: \`${test.file}\` "${test.test}"`;

export function renderOfflineJobMatrix(): string {
  const lines: string[] = [];
  const push = (...text: string[]) => lines.push(...text);

  push(
    '# Offline And Job Execution Matrix',
    '',
    'Generated by `apps/api/src/testing/offline-job-matrix.spec.ts`. Edit the table in',
    '`apps/api/src/testing/offline-job-matrix.ts`, then run',
    '`npm run docs:offline-job-matrix --workspace=@nkwapa/api`. Do not edit this file.',
    '',
    'Every way the offline outbox or a background job could lose a clinician’s work, write it twice,',
    'write it to the wrong clinic, or fail without saying so. Each scenario names its fixture, what',
    'must happen, the surface that owns it, and where it is proven. The suite fails if a named test',
    'disappears or a manual step is missing from the user testing guide.',
    '',
    '## Using it for a release',
    '',
    '1. CI runs every automated row on each push: unit and integration tests in the `test` job, the',
    '   row-level security rows in the tenant isolation step, and the E2E rows in Playwright. Do not',
    '   repeat them by hand.',
    '2. Walk every row marked **Manual** in section 17d of `docs/USER_TESTING_GUIDE.md`, against the',
    '   environment being released. The checklist at the end of this file lists them.',
    '3. Read the known risks. They are tolerated today on purpose and must not be reported as new.',
    '',
  );

  const high = OFFLINE_JOB_SCENARIOS.filter((scenario) => scenario.risk === 'high').length;
  const manual = OFFLINE_JOB_SCENARIOS.filter((scenario) => scenario.manual).length;
  push(
    `${OFFLINE_JOB_SCENARIOS.length} scenarios, ${high} of them high risk; ${manual} also walked by hand.`,
    '',
  );

  for (const condition of MATRIX_CONDITIONS) {
    const { title, intro } = CONDITION_HEADINGS[condition];
    push(`## ${title}`, '', intro, '');
    push('| ID | Scenario | Fixture | Expected | Owner | Risk | Coverage |');
    push('| --- | --- | --- | --- | --- | --- | --- |');
    for (const scenario of OFFLINE_JOB_SCENARIOS.filter((row) => row.condition === condition)) {
      const expected = scenario.knownRisk
        ? `${scenario.expected} (Known risk: ${knownRisks[scenario.knownRisk].title}.)`
        : scenario.expected;
      push(
        `| ${scenario.id} | ${cell(scenario.scenario)} | ${cell(scenario.fixture)} | ${cell(expected)} | ${cell(
          OWNER_SURFACES[scenario.surface],
        )} | ${scenario.risk} | ${coverageCell(scenario)} |`,
      );
    }
    push('');
  }

  push('## Known risks', '');
  if (Object.keys(knownRisks).length === 0) push('None.', '');
  for (const [id, risk] of Object.entries(knownRisks)) {
    const scenarios = OFFLINE_JOB_SCENARIOS.filter((scenario) => scenario.knownRisk === id)
      .map((scenario) => scenario.id)
      .join(', ');
    push(
      `### ${risk.title}`,
      '',
      `Scenarios: ${scenarios}.`,
      '',
      `- **Today:** ${risk.behaviour}`,
      `- **Why it is tolerated:** ${risk.mitigation}`,
      `- **Next:** ${risk.followUp}`,
      '',
    );
  }

  push('## Automated coverage', '', 'The exact tests behind each row.', '');
  for (const scenario of OFFLINE_JOB_SCENARIOS.filter((row) => row.automated.length > 0)) {
    push(`- **${scenario.id}** ${scenario.scenario}`);
    scenario.automated.forEach((test) => push(testLine(test)));
  }
  push('');

  push(
    '## Release validation checklist',
    '',
    'The rows a person walks, in section 17d of `docs/USER_TESTING_GUIDE.md`.',
    '',
  );
  for (const scenario of OFFLINE_JOB_SCENARIOS.filter((row) => row.manual)) {
    push(`- [ ] **${scenario.id}** ${scenario.scenario}`);
  }
  push('');

  return lines.join('\n');
}
