/**
 * Render the patient identity matrix the release gate publishes.
 *
 * Generating the document from the same table the assertions read is what makes the
 * documentation acceptance criterion enforceable: the file cannot describe a rule the code does
 * not implement, because a divergence fails the suite rather than sitting unnoticed in a document
 * nobody re-reads.
 */

import {
  DUPLICATE_CONFIDENCE_THRESHOLDS,
  DUPLICATE_MATCH_REASON_LABELS,
  DUPLICATE_MATCH_WEIGHTS,
  DUPLICATE_NAME_EDIT_DISTANCE,
  MERGE_FINDING_LABELS,
  MERGE_FINDING_RECOVERY,
  isMergeBlockerCode,
} from '@nkwapa/db';

import {
  DUPLICATE_COMBINED_CASE,
  DUPLICATE_RULE_CASES,
  MERGE_FINDING_CASES,
} from './patient-identity-matrix';

export function renderPatientIdentityMatrix(): string {
  const lines: string[] = [];

  lines.push('# Patient Identity Matrix');
  lines.push('');
  lines.push(
    'Generated by `apps/api/src/patients/patient-identity-matrix.spec.ts`. Edit the table in',
  );
  lines.push('`apps/api/src/testing/patient-identity-matrix.ts`, not this file.');
  lines.push('');
  lines.push(
    'Two charts for one person is a clinical safety problem, and consolidating the wrong two is a',
  );
  lines.push(
    'worse one that cannot be undone from the product. These are the rules that decide which pairs',
  );
  lines.push('an operator is shown, and which merges are refused outright.');
  lines.push('');

  lines.push('## Duplicate candidate rules');
  lines.push('');
  lines.push(
    'A pair is scored by summing the weight of every rule it matches, capped at 100. `HIGH` starts',
  );
  lines.push(
    `at ${DUPLICATE_CONFIDENCE_THRESHOLDS.HIGH}, \`MEDIUM\` at ${DUPLICATE_CONFIDENCE_THRESHOLDS.MEDIUM}; below that a pair is \`LOW\`. The weights are chosen so`,
  );
  lines.push(
    'that no single weak signal reaches `MEDIUM` on its own, but any two of them together do.',
  );
  lines.push('');
  lines.push('| Rule | Match | Weight | Alone | What it looks like |');
  lines.push('| --- | --- | --- | --- | --- |');
  for (const rule of DUPLICATE_RULE_CASES) {
    lines.push(
      `| ${DUPLICATE_MATCH_REASON_LABELS[rule.reason]} | ${rule.kind} | ${
        DUPLICATE_MATCH_WEIGHTS[rule.reason]
      } | ${rule.expectedConfidence} | ${rule.staging} |`,
    );
  }
  lines.push('');
  lines.push(
    `Every rule compares normalized values exactly, except the one marked fuzzy: it allows a first`,
  );
  lines.push(
    `name up to ${DUPLICATE_NAME_EDIT_DISTANCE} edits away, and only once the surname and the date of birth already agree.`,
  );
  lines.push('Nothing is ever surfaced on a similarity signal alone.');
  lines.push('');
  const combined = DUPLICATE_COMBINED_CASE.staging.replace(/\.$/, '');
  lines.push(
    `Two weak signals together clear the bar that neither clears alone: ${combined.charAt(0).toLowerCase()}${combined.slice(1)} scores ${DUPLICATE_COMBINED_CASE.expectedScore} and reaches \`${DUPLICATE_COMBINED_CASE.expectedConfidence}\`.`,
  );
  lines.push('');

  lines.push('## Merge refusals');
  lines.push('');
  lines.push(
    'Any one of these stops the merge. The preview reports them before an operator commits, and the',
  );
  lines.push('merge endpoint re-checks them inside its transaction.');
  lines.push('');
  lines.push('| Refusal | What it means | What to do | How to reproduce |');
  lines.push('| --- | --- | --- | --- |');
  for (const finding of MERGE_FINDING_CASES.filter((entry) => isMergeBlockerCode(entry.code))) {
    lines.push(
      `| \`${finding.code}\` | ${MERGE_FINDING_LABELS[finding.code]} | ${
        MERGE_FINDING_RECOVERY[finding.code]
      } | ${finding.staging} |`,
    );
  }
  lines.push('');

  lines.push('## Merge warnings');
  lines.push('');
  lines.push(
    'None of these blocks a merge. They are the consequences worth reading before committing to an',
  );
  lines.push('action with no way back.');
  lines.push('');
  lines.push('| Warning | What it means | What to do | How to reproduce |');
  lines.push('| --- | --- | --- | --- |');
  for (const finding of MERGE_FINDING_CASES.filter((entry) => !isMergeBlockerCode(entry.code))) {
    lines.push(
      `| \`${finding.code}\` | ${MERGE_FINDING_LABELS[finding.code]} | ${
        MERGE_FINDING_RECOVERY[finding.code]
      } | ${finding.staging} |`,
    );
  }
  lines.push('');

  return `${lines.join('\n')}\n`;
}
