import { CLINICAL_RECORD_SURFACES, MATRIX_ROLES, roleHolds } from './clinical-record-surfaces';

/**
 * Render the matrix the release gate publishes.
 *
 * Generating the document from the same table the assertions read is what makes the documentation
 * acceptance criterion enforceable: the file cannot describe a policy the code does not implement,
 * because a divergence fails this suite rather than sitting unnoticed in a doc nobody re-reads.
 */
export function renderRoleMatrix(): string {
  const lines: string[] = [];

  lines.push('# Clinical Records Role Matrix');
  lines.push('');
  lines.push(
    'Generated by `apps/api/src/auth/clinical-record-role-matrix.spec.ts`. Edit the surfaces in',
  );
  lines.push('`apps/api/src/testing/clinical-record-surfaces.ts`, not this file.');
  lines.push('');
  lines.push(
    'Every permission below is evaluated against the roles a user holds **at the clinic being',
  );
  lines.push(
    'read or written**. A role held at another clinic never applies here, and a role held at',
  );
  lines.push('another organization never applies at all.');
  lines.push('');

  for (const surface of CLINICAL_RECORD_SURFACES) {
    lines.push(`## ${surface.label}`);
    lines.push('');
    if (surface.note) {
      lines.push(surface.note);
      lines.push('');
    }

    const columns = [
      { label: 'Read', permission: surface.read },
      { label: 'Write', permission: surface.write },
      ...(surface.additional ?? []),
    ];

    lines.push(`| Role | ${columns.map((c) => c.label).join(' | ')} |`);
    lines.push(`| --- | ${columns.map(() => '---').join(' | ')} |`);
    for (const role of MATRIX_ROLES) {
      const cells = columns.map((column) => (roleHolds(role, column.permission) ? 'yes' : 'no'));
      lines.push(`| ${role} | ${cells.join(' | ')} |`);
    }
    lines.push('');
    lines.push(
      surface.syncEntityTypes.length === 0
        ? 'Offline: not queued. Every read and write requires a live connection.'
        : `Offline: queued as ${surface.syncEntityTypes.map((t) => `\`${t}\``).join(', ')}. The queued write requires the same permission as the online one.`,
    );
    lines.push('');
  }

  lines.push('## Permissions by role');
  lines.push('');
  lines.push('| Permission | ' + MATRIX_ROLES.join(' | ') + ' |');
  lines.push('| --- | ' + MATRIX_ROLES.map(() => '---').join(' | ') + ' |');
  const permissions = [
    ...new Set(
      CLINICAL_RECORD_SURFACES.flatMap((surface) => [
        surface.read,
        surface.write,
        ...(surface.additional ?? []).map((entry) => entry.permission),
      ]),
    ),
  ].sort();
  for (const permission of permissions) {
    const cells = MATRIX_ROLES.map((role) => (roleHolds(role, permission) ? 'yes' : 'no'));
    lines.push(`| \`${permission}\` | ${cells.join(' | ')} |`);
  }
  lines.push('');

  return `${lines.join('\n')}\n`;
}
