export const CLINICAL_NOTE_SECTION_MAX_LENGTH = 20_000;
export const CLINICAL_NOTE_ADDENDUM_REASON_MAX_LENGTH = 500;
export const CLINICAL_NOTE_ADDENDUM_CONTENT_MAX_LENGTH = 20_000;

export const CLINICAL_NOTE_STATUS = {
  DRAFT: 'DRAFT',
  PENDING_COSIGN: 'PENDING_COSIGN',
  COSIGNED: 'COSIGNED',
  AMENDED: 'AMENDED',
} as const;

export type ClinicalNoteStatusValue =
  (typeof CLINICAL_NOTE_STATUS)[keyof typeof CLINICAL_NOTE_STATUS];
