import { UserRole } from '@prisma/client';

export const PERMISSIONS = {
  // Patient
  PATIENT_CREATE: 'PATIENT.CREATE',
  PATIENT_READ: 'PATIENT.READ',
  PATIENT_SEARCH: 'PATIENT.SEARCH',
  /** @deprecated Use PATIENT_SEARCH */
  PATIENT_LIST: 'PATIENT.SEARCH',
  // Encounter
  ENCOUNTER_CREATE: 'ENCOUNTER.CREATE',
  ENCOUNTER_READ: 'ENCOUNTER.READ',
  ENCOUNTER_SUBMIT_FOR_REVIEW: 'ENCOUNTER.SUBMIT_FOR_REVIEW',
  /** @deprecated Use ENCOUNTER_SUBMIT_FOR_REVIEW or ENCOUNTER_READ as appropriate */
  ENCOUNTER_LIST: 'ENCOUNTER.READ',
  // Screening
  SCREENING_WRITE: 'SCREENING.WRITE',
  SCREENING_READ: 'SCREENING.READ',
  // Preceptor
  PRECEPTOR_REVIEW: 'PRECEPTOR.REVIEW',
  // Doctor
  DOCTOR_FINALIZE: 'DOCTOR.FINALIZE',
  CAREPLAN_WRITE: 'CAREPLAN.WRITE',
  // Consent
  CONSENT_RECORD: 'CONSENT.RECORD',
  // Research
  RESEARCH_SETTINGS_UPDATE: 'RESEARCH.SETTINGS.UPDATE',
  RESEARCH_EXPORT_REQUEST: 'RESEARCH.EXPORT.REQUEST',
  RESEARCH_EXPORT_APPROVE: 'RESEARCH.EXPORT.APPROVE',
  // Prescription
  PRESCRIPTION_WRITE: 'PRESCRIPTION.WRITE',
  PRESCRIPTION_READ: 'PRESCRIPTION.READ',
  // Drug
  DRUG_READ: 'DRUG.READ',
  DRUG_MANAGE: 'DRUG.MANAGE',
  // Reminder
  REMINDER_CREATE: 'REMINDER.CREATE',
  REMINDER_READ: 'REMINDER.READ',
  // Clinic
  CLINIC_READ: 'CLINIC.READ',
  CLINIC_MANAGE: 'CLINIC.MANAGE',
  // Audit
  AUDIT_READ: 'AUDIT.READ',
  // Sync
  SYNC_PUSH: 'SYNC.PUSH',
  SYNC_PULL: 'SYNC.PULL',
  // Dashboard
  DASHBOARD_READ: 'DASHBOARD.READ',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

/** Deterministic role-to-permission mapping. Effective permissions = union across roles. */
export const ROLE_PERMISSIONS: Record<UserRole, string[]> = {
  [UserRole.SYSTEM_ADMIN]: ['*'],
  [UserRole.DIRECTOR]: [
    PERMISSIONS.CLINIC_READ,
    PERMISSIONS.CLINIC_MANAGE,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.RESEARCH_SETTINGS_UPDATE,
    PERMISSIONS.RESEARCH_EXPORT_REQUEST,
    PERMISSIONS.RESEARCH_EXPORT_APPROVE,
    PERMISSIONS.PATIENT_READ,
    PERMISSIONS.PATIENT_SEARCH,
    PERMISSIONS.ENCOUNTER_READ,
    PERMISSIONS.SCREENING_READ,
    PERMISSIONS.PRESCRIPTION_READ,
    PERMISSIONS.DRUG_READ,
    PERMISSIONS.DRUG_MANAGE,
    PERMISSIONS.REMINDER_READ,
    PERMISSIONS.SYNC_PUSH,
    PERMISSIONS.SYNC_PULL,
    PERMISSIONS.DASHBOARD_READ,
  ],
  [UserRole.MANAGER]: [
    PERMISSIONS.CLINIC_READ,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.PATIENT_READ,
    PERMISSIONS.PATIENT_CREATE,
    PERMISSIONS.PATIENT_SEARCH,
    PERMISSIONS.ENCOUNTER_CREATE,
    PERMISSIONS.ENCOUNTER_READ,
    PERMISSIONS.ENCOUNTER_SUBMIT_FOR_REVIEW,
    PERMISSIONS.SCREENING_READ,
    PERMISSIONS.PRESCRIPTION_READ,
    PERMISSIONS.DRUG_READ,
    PERMISSIONS.DRUG_MANAGE,
    PERMISSIONS.REMINDER_READ,
    PERMISSIONS.SYNC_PUSH,
    PERMISSIONS.SYNC_PULL,
    PERMISSIONS.DASHBOARD_READ,
  ],
  [UserRole.DOCTOR]: [
    PERMISSIONS.PATIENT_READ,
    PERMISSIONS.PATIENT_CREATE,
    PERMISSIONS.PATIENT_SEARCH,
    PERMISSIONS.ENCOUNTER_CREATE,
    PERMISSIONS.ENCOUNTER_READ,
    PERMISSIONS.ENCOUNTER_SUBMIT_FOR_REVIEW,
    PERMISSIONS.DOCTOR_FINALIZE,
    PERMISSIONS.CAREPLAN_WRITE,
    PERMISSIONS.PRESCRIPTION_WRITE,
    PERMISSIONS.PRESCRIPTION_READ,
    PERMISSIONS.DRUG_READ,
    PERMISSIONS.REMINDER_CREATE,
    PERMISSIONS.REMINDER_READ,
    PERMISSIONS.SCREENING_READ,
    PERMISSIONS.SYNC_PUSH,
    PERMISSIONS.SYNC_PULL,
    PERMISSIONS.DASHBOARD_READ,
  ],
  [UserRole.PRECEPTOR]: [
    PERMISSIONS.PATIENT_READ,
    PERMISSIONS.PATIENT_CREATE,
    PERMISSIONS.SCREENING_READ,
    PERMISSIONS.SCREENING_WRITE,
    PERMISSIONS.PRECEPTOR_REVIEW,
    PERMISSIONS.PATIENT_READ,
    PERMISSIONS.PATIENT_SEARCH,
    PERMISSIONS.ENCOUNTER_READ,
    PERMISSIONS.PRESCRIPTION_READ,
    PERMISSIONS.DRUG_READ,
    PERMISSIONS.SYNC_PUSH,
    PERMISSIONS.SYNC_PULL,
    PERMISSIONS.DASHBOARD_READ,
  ],
  [UserRole.VOLUNTEER]: [
    PERMISSIONS.PATIENT_READ,
    PERMISSIONS.PATIENT_CREATE,
    PERMISSIONS.PATIENT_SEARCH,
    PERMISSIONS.ENCOUNTER_CREATE,
    PERMISSIONS.ENCOUNTER_READ,
    PERMISSIONS.ENCOUNTER_SUBMIT_FOR_REVIEW,
    PERMISSIONS.SCREENING_WRITE,
    PERMISSIONS.CONSENT_RECORD,
    PERMISSIONS.DRUG_READ,
    PERMISSIONS.SYNC_PUSH,
    PERMISSIONS.SYNC_PULL,
    PERMISSIONS.DASHBOARD_READ,
  ],
};

export function hasPermission(
  userRoles: { role: UserRole }[],
  required: string
): boolean {
  for (const { role } of userRoles) {
    const perms = ROLE_PERMISSIONS[role];
    if (perms.includes('*') || perms.includes(required)) {
      return true;
    }
  }
  return false;
}

export function computeEffectivePermissions(roles: UserRole[]): string[] {
  const perms = new Set<string>();
  for (const role of roles) {
    const rolePerms = ROLE_PERMISSIONS[role];
    if (rolePerms.includes('*')) return ['*'];
    for (const p of rolePerms) perms.add(p);
  }
  return [...perms];
}
