// packages/db/index.ts
export { PrismaClient } from '@prisma/client';
export {
  encryptNationalId,
  decryptNationalId,
  hashNationalId,
  nationalIdLast4,
  hasEncryptionKey,
} from './src/national-id';
export { generatePatientCode } from './src/patient-code';
export { normalizePhoneToE164 } from './src/phone';
export {
  computeBmi,
  roundClinicalValue,
  toCelsius,
  type TemperatureUnit,
} from './src/clinical-measurements';
export {
  DIABETES_GLUCOSE_TYPES,
  DIABETES_SYMPTOMS,
  DIABETES_SYMPTOM_LABELS,
  DIABETES_GLUCOSE_MIN_MG_DL,
  DIABETES_GLUCOSE_MAX_MG_DL,
  DIABETES_HBA1C_MIN_PERCENT,
  DIABETES_HBA1C_MAX_PERCENT,
  parseLegacyDiabetesSymptoms,
  serializeLegacyDiabetesSymptoms,
  type DiabetesGlucoseType,
  type DiabetesSymptom,
  type ParsedLegacyDiabetesSymptoms,
} from './src/diabetes-screening';
export {
  CLINICAL_NOTE_SECTION_MAX_LENGTH,
  CLINICAL_NOTE_ADDENDUM_REASON_MAX_LENGTH,
  CLINICAL_NOTE_ADDENDUM_CONTENT_MAX_LENGTH,
  CLINICAL_NOTE_STATUS,
  type ClinicalNoteStatusValue,
} from './src/clinical-notes';
export {
  GHANA_REGIONS,
  GHANA_REGION_LABELS,
  GHANA_DISTRICTS_BY_REGION,
  PATIENT_LOCATION_STATUS_LABELS,
  isGhanaRegion,
  isDistrictInRegion,
  normalizeDistrict,
} from './src/ghana-locations';
export {
  CLINIC_DEFAULT_TIMEZONE,
  CLINIC_DEFAULT_COUNTRY_CODE,
  CLINIC_DEFAULT_ORGANIZATION_NAME,
  CLINIC_DEFAULT_ORGANIZATION_SLUG,
  CLINIC_METADATA_ISSUE_SEVERITY,
  CLINIC_METADATA_SEVERITY_RANK,
  COUNTRY_CODE_LENGTH,
  COUNTRY_CODE_PATTERN,
  LOCATION_CODE_MAX_LENGTH,
  LOCATION_CODE_PATTERN,
  TIMEZONE_MAX_LENGTH,
  TIME_ZONE_NAME_PATTERN,
  ZONE_CODE_MAX_LENGTH,
  ZONE_CODE_PATTERN,
  commonTimeZones,
  evaluateClinicMetadata,
  isCountryCode,
  isLocationCode,
  isTimeZone,
  isZoneCode,
  listTimeZones,
  normalizeCountryCode,
  normalizeLocationCode,
  normalizeZoneCode,
  resolveTimeZone,
  summarizeClinicMetadata,
  toLocationCode,
  type ClinicMetadataField,
  type ClinicMetadataInput,
  type ClinicMetadataIssue,
  type ClinicMetadataIssueCode,
  type ClinicMetadataSeverity,
  type ClinicMetadataSummary,
  type TimeZoneResolution,
} from './src/clinic-metadata';
export {
  clinicDayWindow,
  startOfDayInTimeZone,
  todayInTimeZone,
  type ClinicDayWindow,
} from './src/clinic-day';
export {
  DUPLICATE_CONFIDENCE_LEVELS,
  DUPLICATE_CONFIDENCE_THRESHOLDS,
  DUPLICATE_MATCH_REASONS,
  DUPLICATE_MATCH_REASON_LABELS,
  DUPLICATE_MATCH_WEIGHTS,
  DUPLICATE_NAME_EDIT_DISTANCE,
  duplicatePairKey,
  editDistanceWithin,
  evaluateDuplicatePair,
  normalizeEmailForMatch,
  normalizeNameForMatch,
  parseDuplicatePairKey,
  sameCalendarDay,
  scoreToConfidence,
  type DuplicateCandidateInput,
  type DuplicateConfidence,
  type DuplicateMatchReason,
  type DuplicatePairEvaluation,
} from './src/patient-duplicates';
export {
  CLAIM_REFUSAL_CODES,
  CLAIM_REFUSAL_LABELS,
  CLAIM_REFUSAL_RECOVERY,
  claimRefusal,
  expiredInviteRefusal,
  type ClaimRefusal,
  type ClaimRefusalCode,
} from './src/patient-claim';
export {
  MERGE_BLOCKER_CODES,
  MERGE_FINDING_LABELS,
  MERGE_FINDING_RECOVERY,
  MERGE_RELATIONS,
  MERGE_SPECIAL_CASE_MODELS,
  MERGE_WARNING_CODES,
  isMergeBlocked,
  isMergeBlockerCode,
  mergeFinding,
  mergePreviewFingerprint,
  type MergeBlockerCode,
  type MergeFinding,
  type MergeFindingCode,
  type MergeFingerprintInput,
  type MergeRelationKey,
  type MergeWarningCode,
} from './src/patient-merge';
export {
  PATIENT_CHART_SECTION_IDS,
  PATIENT_CHART_SECTIONS,
  canAccessPatientChartSection,
  getPatientChartSection,
  isPatientChartSectionId,
  resolveAccessiblePatientChartSections,
  resolvePatientChartSectionId,
  type PatientChartAccessInput,
  type PatientChartFeatureFlag,
  type PatientChartSection,
  type PatientChartSectionId,
} from './src/patient-chart-sections';
export {
  TENANT_ORGANIZATIONS,
  TENANT_CLINICS,
  TENANT_CLINICAL_ROLES,
  TENANT_CROSS_CLINIC_USERS,
  TENANT_SYSTEM_ADMIN,
  TENANT_USERS,
  TENANT_PATIENTS,
  tenantUser,
  tenantFixtureSql,
  type TenantFixtureRole,
  type TenantFixtureOrganization,
  type TenantFixtureClinic,
  type TenantFixtureRoleGrant,
  type TenantFixtureUser,
  type TenantFixturePatient,
} from './src/testing/tenant-fixture';
export {
  confirmedVisitStart,
  terminalVisitStart,
  weekStartUtc,
  isInVisibleWeek,
} from './src/appointment-fixture-window';
