// packages/db/index.ts
export { PrismaClient } from '@prisma/client';
export {
  encryptNationalId,
  decryptNationalId,
  hashNationalId,
  nationalIdLast4,
  hasEncryptionKey,
} from './src/national-id';
export { generatePatientCode } from './src/patient-code';
export { normalizePhoneToE164 } from './src/phone';
export {
  computeBmi,
  roundClinicalValue,
  toCelsius,
  type TemperatureUnit,
} from './src/clinical-measurements';
export {
  DIABETES_GLUCOSE_TYPES,
  DIABETES_SYMPTOMS,
  DIABETES_SYMPTOM_LABELS,
  DIABETES_GLUCOSE_MIN_MG_DL,
  DIABETES_GLUCOSE_MAX_MG_DL,
  DIABETES_HBA1C_MIN_PERCENT,
  DIABETES_HBA1C_MAX_PERCENT,
  parseLegacyDiabetesSymptoms,
  serializeLegacyDiabetesSymptoms,
  type DiabetesGlucoseType,
  type DiabetesSymptom,
  type ParsedLegacyDiabetesSymptoms,
} from './src/diabetes-screening';
export {
  CLINICAL_NOTE_SECTION_MAX_LENGTH,
  CLINICAL_NOTE_ADDENDUM_REASON_MAX_LENGTH,
  CLINICAL_NOTE_ADDENDUM_CONTENT_MAX_LENGTH,
  CLINICAL_NOTE_STATUS,
  type ClinicalNoteStatusValue,
} from './src/clinical-notes';
export {
  GHANA_REGIONS,
  GHANA_REGION_LABELS,
  GHANA_DISTRICTS_BY_REGION,
  PATIENT_LOCATION_STATUS_LABELS,
  isGhanaRegion,
  isDistrictInRegion,
  normalizeDistrict,
} from './src/ghana-locations';
export {
  CLINIC_DEFAULT_TIMEZONE,
  CLINIC_DEFAULT_COUNTRY_CODE,
  CLINIC_DEFAULT_ORGANIZATION_NAME,
  CLINIC_DEFAULT_ORGANIZATION_SLUG,
  CLINIC_METADATA_ISSUE_SEVERITY,
  CLINIC_METADATA_SEVERITY_RANK,
  COUNTRY_CODE_LENGTH,
  COUNTRY_CODE_PATTERN,
  LOCATION_CODE_MAX_LENGTH,
  LOCATION_CODE_PATTERN,
  TIMEZONE_MAX_LENGTH,
  TIME_ZONE_NAME_PATTERN,
  ZONE_CODE_MAX_LENGTH,
  ZONE_CODE_PATTERN,
  commonTimeZones,
  evaluateClinicMetadata,
  isCountryCode,
  isLocationCode,
  isTimeZone,
  isZoneCode,
  listTimeZones,
  normalizeCountryCode,
  normalizeLocationCode,
  normalizeZoneCode,
  resolveTimeZone,
  summarizeClinicMetadata,
  toLocationCode,
  type ClinicMetadataField,
  type ClinicMetadataInput,
  type ClinicMetadataIssue,
  type ClinicMetadataIssueCode,
  type ClinicMetadataSeverity,
  type ClinicMetadataSummary,
  type TimeZoneResolution,
} from './src/clinic-metadata';
export {
  clinicDayWindow,
  startOfDayInTimeZone,
  todayInTimeZone,
  type ClinicDayWindow,
} from './src/clinic-day';
export {
  UNZONED_FILTER_VALUE,
  UNZONED_LABEL,
  isZoneFilterValue,
  listZoneCodes,
  parseZoneFilter,
  summarizeZones,
  zoneFilterMatches,
  zoneFilterWhere,
  zoneLabel,
  zoneSummaryFilterValue,
  type ZoneFilter,
  type ZoneSummary,
} from './src/clinic-zones';
export {
  DUPLICATE_CONFIDENCE_LEVELS,
  DUPLICATE_CONFIDENCE_THRESHOLDS,
  DUPLICATE_MATCH_REASONS,
  DUPLICATE_MATCH_REASON_LABELS,
  DUPLICATE_MATCH_WEIGHTS,
  DUPLICATE_NAME_EDIT_DISTANCE,
  duplicatePairKey,
  editDistanceWithin,
  evaluateDuplicatePair,
  normalizeEmailForMatch,
  normalizeNameForMatch,
  parseDuplicatePairKey,
  sameCalendarDay,
  scoreToConfidence,
  type DuplicateCandidateInput,
  type DuplicateConfidence,
  type DuplicateMatchReason,
  type DuplicatePairEvaluation,
} from './src/patient-duplicates';
export {
  CLAIM_REFUSAL_CODES,
  CLAIM_REFUSAL_LABELS,
  CLAIM_REFUSAL_RECOVERY,
  claimRefusal,
  expiredInviteRefusal,
  type ClaimRefusal,
  type ClaimRefusalCode,
} from './src/patient-claim';
export {
  MERGE_BLOCKER_CODES,
  MERGE_FINDING_LABELS,
  MERGE_FINDING_RECOVERY,
  MERGE_RELATIONS,
  MERGE_SPECIAL_CASE_MODELS,
  MERGE_WARNING_CODES,
  isMergeBlocked,
  isMergeBlockerCode,
  mergeFinding,
  mergePreviewFingerprint,
  type MergeBlockerCode,
  type MergeFinding,
  type MergeFindingCode,
  type MergeFingerprintInput,
  type MergeRelationKey,
  type MergeWarningCode,
} from './src/patient-merge';
export {
  PATIENT_CHART_SECTION_IDS,
  PATIENT_CHART_SECTIONS,
  canAccessPatientChartSection,
  getPatientChartSection,
  isPatientChartSectionId,
  resolveAccessiblePatientChartSections,
  resolvePatientChartSectionId,
  type PatientChartAccessInput,
  type PatientChartFeatureFlag,
  type PatientChartSection,
  type PatientChartSectionId,
} from './src/patient-chart-sections';
export {
  SHARED_ZONE_CODE,
  TENANT_ORGANIZATIONS,
  TENANT_CLINICS,
  TENANT_CLINICAL_ROLES,
  TENANT_CROSS_CLINIC_USERS,
  TENANT_SYSTEM_ADMIN,
  TENANT_USERS,
  TENANT_PATIENTS,
  tenantUser,
  tenantFixtureSql,
  type TenantFixtureRole,
  type TenantFixtureOrganization,
  type TenantFixtureClinic,
  type TenantFixtureRoleGrant,
  type TenantFixtureUser,
  type TenantFixturePatient,
} from './src/testing/tenant-fixture';
export {
  confirmedVisitStart,
  terminalVisitStart,
  weekStartUtc,
  isInVisibleWeek,
} from './src/appointment-fixture-window';

export {
  NKWAPA_ANSWERS,
  NKWAPA_ANSWER_LABELS,
  FREQUENCY_NEVER_SOMETIMES_USUALLY,
  FREQUENCY_NEVER_SOMETIMES_USUALLY_LABELS,
  FREQUENCY_NEVER_SOMETIMES_DAILY,
  FREQUENCY_NEVER_SOMETIMES_DAILY_LABELS,
  FREQUENCY_RARELY_SOME_MOST,
  FREQUENCY_RARELY_SOME_MOST_LABELS,
  FREQUENCY_NEVER_SOMETIMES_OFTEN,
  FREQUENCY_NEVER_SOMETIMES_OFTEN_LABELS,
  SCREENING_COMPLETION_STATUSES,
  SCREENING_COMPLETION_STATUS_LABELS,
  MEDICATION_USE_STATUSES,
  MEDICATION_USE_STATUS_LABELS,
  MEDICATION_SUPPLY_STATUSES,
  MEDICATION_SUPPLY_STATUS_LABELS,
  MEDICATION_ADHERENCE_LEVELS,
  MEDICATION_ADHERENCE_LEVEL_LABELS,
  MEDICATION_DOSES_MISSED,
  MEDICATION_DOSES_MISSED_LABELS,
  MEDICATION_PROBLEMS,
  MEDICATION_PROBLEM_LABELS,
  MEDICATION_REMINDER_STRATEGIES,
  MEDICATION_REMINDER_STRATEGY_LABELS,
  TOBACCO_USE_STATUSES,
  TOBACCO_USE_STATUS_LABELS,
  ALCOHOL_USE_STATUSES,
  ALCOHOL_USE_STATUS_LABELS,
  MEALS_PER_DAY_BANDS,
  MEALS_PER_DAY_BAND_LABELS,
  FOLLOW_UP_WINDOWS,
  FOLLOW_UP_WINDOW_LABELS,
  FOLLOW_UP_OWNERS,
  FOLLOW_UP_OWNER_LABELS,
  resolveFollowUpDate,
  type NkwapaAnswerValue,
  type FrequencyNeverSometimesUsuallyValue,
  type FrequencyNeverSometimesDailyValue,
  type FrequencyRarelySomeMostValue,
  type FrequencyNeverSometimesOftenValue,
  type ScreeningCompletionStatusValue,
  type MedicationUseStatusValue,
  type MedicationSupplyStatusValue,
  type MedicationAdherenceLevelValue,
  type MedicationDosesMissedValue,
  type MedicationProblemValue,
  type MedicationReminderStrategyValue,
  type TobaccoUseStatusValue,
  type AlcoholUseStatusValue,
  type MealsPerDayBandValue,
  type FollowUpWindowValue,
  type FollowUpOwnerValue,
} from './src/clinical-vocabulary';
export {
  HYPERTENSION_CLASSIFICATIONS,
  BP_THRESHOLDS,
  BP_SYSTOLIC_MIN,
  BP_SYSTOLIC_MAX,
  BP_DIASTOLIC_MIN,
  BP_DIASTOLIC_MAX,
  BP_REPEAT_PROMPT_SYSTOLIC,
  BP_REPEAT_PROMPT_DIASTOLIC,
  BP_ESCALATION_SYSTOLIC,
  BP_ESCALATION_DIASTOLIC,
  BP_HYPOTENSION_SYSTOLIC,
  BP_HYPOTENSION_DIASTOLIC,
  classifyBloodPressure,
  shouldPromptRepeat,
  isSeverelyElevated,
  isHypotensive,
  type HypertensionClassificationValue,
} from './src/bp-classification';
export {
  PHQ2_RESPONSES,
  PHQ2_RESPONSE_LABELS,
  PHQ2_RESPONSE_SCORES,
  PHQ2_MIN_SCORE,
  PHQ2_MAX_SCORE,
  PHQ2_POSITIVE_THRESHOLD,
  DIABETES_DISTRESS_RESPONSES,
  DIABETES_DISTRESS_RESPONSE_LABELS,
  DIABETES_DISTRESS_POSITIVE_SEVERITY,
  phq2Total,
  isPhq2Positive,
  isDiabetesDistressPositive,
  type Phq2Response,
  type DiabetesDistressResponse,
} from './src/phq2';
export {
  DIABETES_GLUCOSE_CONTEXTS,
  DIABETES_GLUCOSE_CONTEXT_LABELS,
  DIABETES_SUSPICION_RESULTS,
  DM_FASTING_SUSPICION_MG_DL,
  DM_RANDOM_SUSPICION_MG_DL,
  DM_BEFORE_MEAL_SUSPICION_MG_DL,
  DM_POST_PRANDIAL_2H_SUSPICION_MG_DL,
  DM_HYPOGLYCEMIA_MG_DL,
  suspicionThresholdFor,
  evaluateGlucoseSuspicion,
  isHypoglycemic,
  type DiabetesGlucoseContext,
  type DiabetesSuspicionResult,
} from './src/diabetes-thresholds';
export {
  CHRONIC_CONDITIONS,
  HYPERTENSION_DRUG_CATEGORIES,
  DIABETES_DRUG_CATEGORIES,
  drugCategoriesForCondition,
  isCategoryForCondition,
  type ChronicCondition,
  type ChronicDrugCategory,
} from './src/medication-classes';
export {
  PayloadIssues,
  readObject,
  readEnum,
  readEnumArray,
  readBoolean,
  readInteger,
  readText,
  readSchemaVersion,
  rejectUnknownKeys,
  type PayloadIssue,
  type PayloadIssueCode,
  type ParsedPayload,
} from './src/payload-contract';
export * from './src/hypertension-interview';
export * from './src/diabetes-interview';
